### ISSUE TITLE
async/await version

### ISSUE THREAD

**Issue by trevera2** [maxmind/GeoIP2-dotnet#1]
Hi,

Please add a non-blocking async/await version, so we can call it this way:

var client = new WebServiceClient(42, "abcdef12345");
var omni = await client.OmniAsync("128.101.101.101");

It's very important for programs that using .NET 4.5 or a later version.

**Comment by niemyjski** [comment]
Please support .net 4.0 or above. It would be really nice to support pcl which would get you ready to support vnext.

**Comment by niemyjski** [comment]
:+1:

**Comment by niemyjski** [comment]
For the love of god please revert your async changes relating to the bcl. the second you bring in the bcl async libraries you just created a virus for anyone who wants to use your library... It requires every project in your solution to reference it and becomes a PITA.

**Comment by niemyjski** [comment]
It's better to just not target any framework that doesn't support async await than to bring in the dependency on the bcl async stuff.

**Comment by oschwald** [comment]
Thanks for your input. If there is enough demand, we may modify our NuGet package to target multiple frameworks with the BCL/Microsoft.Net.Http dependency only required for .NET 4.0.

**Comment by niemyjski** [comment]
I'd highly consider this... We tried going down this path with our oss projects about a year ago and got lots of feedback and  went through a lot of struggling. We ended up giving up on async completely in https://github.com/exceptionless/Exceptionless.Net as it just isn't viable in portable environments due to the bcl async packages. We're converting https://github.com/exceptionless/Foundatio to be 100% async now and we are only supporting 4.5 (one of the main reasons is the bcl). I figured I should let you guys know.. cause we went through these issues.. The biggest one is a forced dependency on all your consumers to have the bcl async dependencies in all projects in a solution that references the bcl async.
