### ISSUE TITLE
NuGet package, C#

### ISSUE THREAD

**Issue by RKayCH** [maxmind/GeoIP2-dotnet#103]
Im facing an issue with the Webclient from the GeoIP2 nuget package, getting the error:
"The request was aborted: Could not create SSL/TLS secure channel.". 

The error is not constantly occuring. It's very periodic, half a day - then just a few requests, then a few hours nonstop. 

I'm using the nuget package without any modifications, tried switching from async to sync to eliminate any issues. 

Any hint where i could look for potential issues on my side? Networking erros i could eliminate... no other SSL-encrypted request fails.

**Comment by oschwald** [comment]
This library just uses `HttpClient` for async requests and `WebRequest` for sync requests. It doesn't do anything special related to SSL/TLS. I would suggest contacting [support@maxmind.com](mailto:support@maxmind.com) as they will be able to look at the particulars of your traffic to see if anything seems amiss.

**Comment by InvokeExpression** [comment]
MaxMind turned off support for TLS1.0 a couple weeks ago and HttpClient defaults to TLS1.0.

You can adjust the TLS version HttpClient uses by adding the following line before you make any calls to MaxMind:

System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;

**Comment by ak37165** [comment]
Thought this clarification may help: I was not using HttpClient but MaxMind.GeoIP2.WebServiceClient to make the API call. Adding the line System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12; still worked (likely because the MaxMind library internally uses HttpClient and since ServicePointManager is a static class, its settings affects all instances of HttpClient).
