### ISSUE TITLE
Load all databases (City, Country, ASN) on startup

### ISSUE THREAD

**Issue by b0xCH** [maxmind/GeoIP2-dotnet#212]
I am currently trying to implement a backend service which in the end should be able to do IP lookups with the three databases "City", "Country" and "ASN".

For performance reasons, I'd like to initiate the DatabaseReader on startup and then utilize it whenever I want to do a Query, so that the DB-File does not need to be accessed for every lookup.

To do so, I tried to add this to "Program.cs":
`builder.Services.AddSingleton(maxmindASN => new DatabaseReader("GeoLite2-ASN.mmdb"));`

This works and I'm able to query data. However, when I want to add the "City" and "Country" databases, I am unable to register them the same way, as only one of the 3 DBs is initiated.

Is there any recommended way on how to initiate the 3 DBs in the same application on startup, so that they can be shared? 

Thanks in advance!

**Comment by oschwald** [comment]
I don't think the issue is at the `DatabaseReader` level. You can initialize multiple readers and use them. For instance, this simple program:

```
using MaxMind.GeoIP2;

var asnReader = new DatabaseReader("/usr/local/share/GeoIP/GeoLite2-ASN.mmdb");
var cityReader = new DatabaseReader("/usr/local/share/GeoIP/GeoLite2-City.mmdb");

Console.WriteLine(asnReader.Asn("128.101.101.101").AutonomousSystemOrganization);
Console.WriteLine(cityReader.City("128.101.101.101").City.Name);
```

produces:

```
UMN-SYSTEM
Minneapolis
```

Perhaps if you remove your exception handling, you will see the underlying cause of the issue. It is a bit hard to diagnose this further without a complete runnable example. I am guessing this is actually an ASP.NET issue that is not specific to this library. I'd suggest asking on Stack Overflow or an online forum.

**Comment by oschwald** [comment]
Closing as I don't believe there to be an actionable issue with the library.
