### ISSUE TITLE
DatabaseReader slow

### ISSUE THREAD

**Issue by oliverw** [maxmind/GeoIP2-dotnet#37]
Judging from the [published Benchmarks](https://dev.maxmind.com/geoip/legacy/benchmarks/#C-based_APIs), the DatabaseReader appears to be quite slow. Actually by several orders of magnitude slower than the Java API.

I've wrote a test against GeoLite2-Country.mmdb. And on my Core i7 Development machine I was only to perform approx. 20k queries/sec. At first I thought that initializing the reader with a stream rather than a file which turns off caching. Picture my surprise when switching to a reader using memory-mapped-file based caching resulted in barely 11k queries/sec.

**Comment by oschwald** [comment]
Those benchmarks are for the GeoIP Legacy API with a 32-bit (IPv4) search tree. The Legacy databases contain much less data.

That said, the .NET API is slower than the GeoIP2 Java API. We would be happy to accept reasonable pull requests that do not change the API to improve this.

**Comment by niemyjski** [comment]
+1

**Comment by lepipele** [comment]
@oliverw I took quick look through source code and it's obvious that whoever did this library is C# n00b. It's enough to see using exceptions for flow control and you know how well versed they are in the language. I doubt I'll have time to improve library but will definitely fork it and make my own flavor... no way it can go in production like this...

And if any of you MaxMind guys are looking at this thread please read the link I'm leaving and do whatever you can to fix the library: http://stackoverflow.com/questions/891217/how-expensive-are-exceptions-in-c

**Comment by oschwald** [comment]
@lepipele, there are already `Try*` methods that do not throw the not-found exception. Also, if you are getting this exception frequently, you likely have an integration problem. MaxMind databases have almost all public IP addresses that have been allocated. Receiving this exception enough to cause performance issues suggests that you are passing the IP address of your internal load balancer, proxy server, etc.

Also, the reader should be much faster than when this issue was created. The actual performance problems are _not_ related to exception handling but deserializing the data to classes efficiently.

**Comment by lepipele** [comment]
Yeah - I figured out those Try methods an hour ago... out parameter always makes me cringe but it'll have to do for now, I guess. I've tried installing required things on my machine in order to compile your libraries but seems that will also take more time than I have.

Anyways - I'm now even more curious to see what's the big problem deserialization to classes shouldn't be that resource intensive to make C# code slower than Java. If I do make some improvements I'll try with pull request.

**Comment by oschwald** [comment]
To compile, you just need the latest `dotnet/cli`. You can then just do a `dotnet restore` and a `dotnet build`.

Also, you don't need to use `MaxMind.GeoIP2`. If you only need a subset of the fields, using `MaxMind.Db` directly with a paired down model class _will_ be faster as it only deserializes the data it needs for the class.

**Comment by oschwald** [comment]
Closing as this issue is so general that it is not actionable. There have been significant improvements to the underlying `MaxMind.Db` library in the past 4 years and reasonable PRs to improve performance without changing the API would happily be accepted.
